### ISSUE TITLE
Alias not shown in Dashboard

### ISSUE THREAD

**Issue by feinfinger** [waltz-controls/waltz#240]
In the dashboard profiles it was possible to make a table with device attributes and the alias name of the device. This still works, but when reopening Waltz, the alias names in the dashboard are not shown anymore, but the motor tango device names are shown instead. Would it be possible to make the column Device selectable for Tango device name / alias?

**Comment by Ingvord** [comment]
@feinfinger thanks for reporting this issue.

This is a known issue due to #225. The problem is that when one reopens Waltz Dashboard fetches device names from the UserContext. At that point Dashboard does not know anything about aliases... seems that easy-to-do fix is to store aliases along with device names in the UserContext.

Also adding switch between aliases and names sounds like a good idea to me. Thanks for the hint!

**Comment by Ingvord** [comment]
Should be deployed with the next release!
